---
comments: false
pagetitle: 'Mediation - Mediation'
---

## Mediation - Moderation 

You've come to the right place to learn mediation and moderation! This page serves to include the links for the videos from my YouTube Channel that include PROCESS v 2, PROCESS v 3, JASP, and R videos. 

- **Cite**: Buchanan, E. M. (2020, March 15). Mediation - Moderation Examples. https://doi.org/10.17605/OSF.IO/NS6JZ  
- **OSF Page**: https://osf.io/ns6jz/
- **GitHub Page**: https://github.com/doomlab/MeMoBootR

```{r echo = F, message = F}
library(rio)
library(kableExtra)
library(dplyr)
page <- "med_mod"

yt_data <- import(paste0(here::here(), "/no_sync/youtube_updated.xlsx"))

yt_data <- subset(yt_data, page == page)
```

```{r echo = F, results = 'asis', warning = F}
kable(yt_data %>% 
       #filter(program == "SPSS" | program == "na") %>% 
        filter(order != "extra") %>% 
        arrange(-desc(as.numeric(order))) %>%
        select(section, title, link, materials, person, year_taught),
      col.names = c("Section", "Title", "Link", "Materials", "Person", "Year Taught")) %>% 
  kable_styling(bootstrap_options = c("hover"), font_size = 13)
```
