---
comments: false
pagetitle: 'Open Science'
---

## Open Science

**Page description:** Tutorials on various packages for _R Markdown_ and reproducible analyses. 

- **Cite**: Buchanan, E. M. (2020, March 15). Reproducible Analyses. https://doi.org/10.17605/OSF.IO/8TVMC 
- **OSF Page**: https://osf.io/8tvmc/
- **GitHub Page**: https://github.com/doomlab/statsofdoom-files/tree/master/open_science

```{r echo = F, message = F}
library(rio)
library(kableExtra)
library(dplyr)
page <- "open"

yt_data <- import(paste0(here::here(), "/no_sync/youtube_updated.xlsx"))

yt_data <- yt_data[!is.na(yt_data$open_science), ]
```

```{r echo = F, results = 'asis', warning = F}
kable(yt_data %>% 
       #filter(program == "SPSS" | program == "na") %>% 
        filter(open_science_order != "extra") %>% 
        arrange(-desc(as.numeric(open_science_order))) %>%
        select(open_science, title, link, materials, person, year_taught),
      col.names = c("Section", "Title", "Link", "Materials", "Person", "Year Taught")) %>% 
  kable_styling(bootstrap_options = c("hover"), font_size = 13)
```
